# Site settings
title: Grayscale
email: benmelosh@gmail.com
url: https://example.github.io
description: A portfolio of recent projects, maps and geoscience tools.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: BenjiDa

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/rolltheturbines
  - title: google scholar
    url: https://scholar.google.com/citations?user=8ijDU1MAAAAJ&hl=en
  - title: github
    url: https://github.com/BenjiDa
  - title: linkedin
    url: https://www.linkedin.com/in/ben-melosh-7043a859/
  - title: Publications
    url: 
  - title: Curriculum Vitae
    url: 


# Build settings
markdown: kramdown
permalink: pretty
